### Docker Compose file for Nginx

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    env_file:
      - ../.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./sites-enabled:/etc/nginx/sites-enabled
      - ./sites-available:/etc/nginx/sites-available
      - ./snippets:/etc/nginx/snippets
    networks:
      keycloak_network:
        external: true