version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./sites-enabled:/etc/nginx/sites-enabled
      - ./sites-available:/etc/nginx/sites-available
      - ./snippets:/etc/nginx/snippets
    depends_on:
      - minio
    networks:
      - datagang

  minio:
    image: quay.io/minio/minio
    container_name: minio-datagang
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-miniodatagang}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-123456789}
      - MINIO_API_PORT=${MINIO_API_PORT:-9000}
      - MINIO_CONSOLE_PORT=${MINIO_CONSOLE_PORT:-9001}
      - MINIO_BROWSER_REDIRECT_URL=${MINIO_BROWSER_REDIRECT_URL:-https://minio-console.example.com}
    volumes:
      - ./data:/data
    ports:
      - ${MINIO_API_PORT:-9000}:${MINIO_API_PORT:-9000}
      - ${MINIO_CONSOLE_PORT:-9001}:${MINIO_CONSOLE_PORT:-9001}
    command: server /data --console-address ":${MINIO_CONSOLE_PORT:-9001}"
    networks:
      - datagang