services:
  minio:
    image: quay.io/minio/minio
    container_name: minio-datagang
    profiles:
      - minio
      - storage
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-miniodatagang}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-123456789}
      - MINIO_BROWSER_REDIRECT_URL=${MINIO_BROWSER_REDIRECT_URL:-https://minio-console.example.com}
    volumes:
      - ./data:/data
    ports:
      - ${MINIO_API_PORT:-9000}:${MINIO_API_PORT:-9000}
      - ${MINIO_CONSOLE_PORT:-9001}:${MINIO_CONSOLE_PORT:-9001}
    command: server /data --console-address ":${MINIO_CONSOLE_PORT:-9001}"
